const columns = [
    { name: "Customized Instructions", uid: "customizedInstructions" },
    { name: "Posted (?hours Ago)", uid: "time" },
    {name: "FORMAT", uid: "format"},
    {name: "STATUS", uid: "status"},
    {name: "ACTIONS", uid: "actions"},


  ];
  
  const orders = [
    {
      id: 1,
      page: 5,
      urgency: 3,
      format: "APA",
      customizedInstructions: "Please follow the attached guidelines.",
      instructionFiles: "guidelines.pdf",
      qualityLevel: "University",
      sourcesToBeCited: 10,
      time: 5,
      status: "Draft",
      createdAt: "2023-05-01T10:00:00Z",
      updatedAt: "2023-05-02T12:00:00Z",
    },
    {
      id: 2,
      page: 10,
      urgency: 2,
      format: "MLA",
      customizedInstructions: "Make sure to include recent sources.",
      instructionFiles: "sources.pdf",
      qualityLevel: "Masters",
      sourcesToBeCited: 15,
      time:2,
      status: "Picked",
      createdAt: "2023-06-15T14:00:00Z",
      updatedAt: "2023-06-16T16:00:00Z",
    },
    {
      id: 3,
      page: 7,
      urgency: 1,
      format: "Harvard",
      customizedInstructions: "Follow the Harvard citation style strictly.",
      instructionFiles: "citation_style.pdf",
      qualityLevel: "PhD",
      sourcesToBeCited: 8,
      time: 1,
      status: "Not_picked",
      createdAt: "2023-07-20T09:00:00Z",
      updatedAt: "2023-07-21T11:00:00Z",
    },
    {
      id: 4,
      page: 3,
      urgency: 5,
      format: "Chicago",
      customizedInstructions: "No specific instructions.",
      instructionFiles: "none",
      qualityLevel: "High_school",
      sourcesToBeCited: 5,
      time:3,
      status: "Picked",
      createdAt: "2023-08-10T08:00:00Z",
      updatedAt: "2023-08-11T10:00:00Z",
    },
    {
      id: 5,
      page: 12,
      urgency: 4,
      format: "Other",
      customizedInstructions: "Use any style that fits.",
      instructionFiles: "any_style.pdf",
      qualityLevel: "College",
      sourcesToBeCited: 12,
      time:4,
      status: "Not_picked",
      createdAt: "2023-09-05T15:00:00Z",
      updatedAt: "2023-09-06T17:00:00Z",
    },
  ];
  
  export { columns, orders };
  